[build]
  command = "npm install && npx update-browserslist-db@latest && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_BASE_URL = "/"
  NPM_FLAGS = "--no-audit --no-fund"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000" 